### ISSUE TITLE
git-lfs?

### ISSUE THREAD

**Issue by charlieroberts** [tidalcycles/Clean-Samples#1]
I was thinking that samples should be stored using git-lfs (https://git-lfs.github.com). Thoughts?

**Comment by yaxu** [comment]
I've not heard of it before, but sounds sensible!

**Comment by yaxu** [comment]
Will make sense to use this in some cases but after discussion here I think storage method is out of scope for agreeing on a shared metadata format. 
https://github.com/tidalcycles/Clean-Samples/issues/3
