### ISSUE TITLE
Quarks as sample sets

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/Clean-Samples#6]
I'm a bit worried about polluting the supercollider quarks database with a lot of sample sets. What do you think @telephon ? Maybe at least a good idea to encourage people to prefix the name of their quarks with e.g. `Samples-` or `Clean-`?

**Comment by yaxu** [comment]
Also, do we need to do something to allow SuperDirt to find these? Or can it just look for files like `../*/*.cleanmeta` (in which case all the .cleanmeta files would have to be in the root folder of the quark repos).

**Comment by yaxu** [comment]
I separated out the example samples into its own repo, turned both repos into quarks and submitted a PR: https://github.com/supercollider-quarks/quarks/pull/105

**Comment by yaxu** [comment]
PR accepted!
@cleary I updated the instructions here - https://github.com/tidalcycles/Clean-Samples
Is there enough there for you to create metadata for yours? Not sure if you want to make a single pack with more than one set of samples like I've done with https://github.com/tidalcycles/Clean-repetition , or contribute each set of samples as its own repo. In the latter case to match things up you'd have to rename the repo to e.g. Clean-flbass. Without that it'll be a bit messy for the quarks database.

**Comment by cleary** [comment]
@yaxu that all looks ok - I'm thinking that I'll create a single pack repo full of submodule references though (rather than duplicate all the repos), will that work in this scenario?

**Comment by telephon** [comment]
> I'm a bit worried about polluting the supercollider quarks database with a lot of sample sets. What do you think @telephon ? Maybe at least a good idea to encourage people to prefix the name of their quarks with e.g. `Samples-` or `Clean-`?

Quarks need not be in the database, and you can add them simply by path. This can be handled from SuperDirt.

**Comment by telephon** [comment]
There could be one quark that just contains a list of all the sample repositories in the dependencies. There is no need for the sample repositiories to "be" quarks. One could even do the updating from superdirt, just with a few simple git commands.

**Comment by yaxu** [comment]
@telephon Ah great, yes that's much easier.

**Comment by telephon** [comment]
The main UI issue is how to select and reject samplebanks.

**Comment by yaxu** [comment]
Your quark is installing now @cleary without having to be registered in the supercollider quarks, but unfortunately not with submodules. 
@telephon Yes it would be good to think about the UI before going further. I'll remove Clean-repetition from the main quark directory for now.

**Comment by yaxu** [comment]
@cleary how about this sort of thing https://github.com/cleary/samples-cello-plucked/pull/1

**Comment by yaxu** [comment]
I started moving the old samples into here, where license etc is known: https://github.com/yaxu/Clean-Dirty

**Comment by yaxu** [comment]
A thought - I guess we are conflating a few different aims:
1/ a set of curated default samples for superdirt, so beginners can jump in straight away, for use in example patterns, as a common base for sharing ideas, as well as more generally usable
2/ a larger directory of samplepacks that people can selectively install/uninstall
3/ a general metadata format for sharing samples between people

If 2/ gets easy then 1/ can get smaller, out of consideration those with low bandwidth/disk space.

**Comment by telephon** [comment]
Since the samples are what makes tidal code work, they are a real dependency of tidal code. I don't know if this is solvable. But it is a reason not to reduce the default too much, I suppose?

**Comment by yaxu** [comment]
@telephon Yes perhaps we could have a SuperDirt-lite package for people with poor internet access. In reality though the haskell install is probably the bigger part, so a smaller binary distribution on the tidal side is a priority there.

There's a lot of samples in the current pack to go through..  https://github.com/yaxu/sounds-dirty/issues/1

**Comment by yaxu** [comment]
I decided to encourage the prefix 'sounds-' for repo names, as we'll add synthdefs to the mix later.

**Comment by yaxu** [comment]
Going through trying to remember where these came from.. https://github.com/tidalcycles/sounds-dirty/issues/1
