### ISSUE TITLE
Clean-cleary-samples - submodules removed

### ISSUE THREAD

**Issue by cleary** [tidalcycles/Clean-Samples#9]
Hi @yaxu, 
I've updated my sample set to 

 - not use submodules 
 - move the cleanmeta file into the subdir containing the samples 

Could you give it another update/try please?

Also, I'm still working on the cello sets for the moment, so I've left them out - once I've got their layout confirmed I will move them in -

[edit] Quick question, is the `Clean-` prefix still required? I'd rather not maintain a separate repository just for this - ideally I'd  just like to add the orig sample repos to the quark deps

**Comment by yaxu** [comment]
Yes I was thinking the same - ditch `Clean-cleary-samples` and add `samples-flbass` directly to the deps of this repository.

Now we're not in the main supercollider quark namespace I don't think we need to stick `Clean-` in front of everything. `samples-` is fine as a prefix and we can recommend that for other contributions.

**Comment by cleary** [comment]
great! I'll get an updated pr shortly :)

**Comment by yaxu** [comment]
@cleary I already updated the Clean-samples.quark https://github.com/tidalcycles/Clean-Samples/blob/main/Clean-Samples.quark
